### ISSUE TITLE
TypeError: Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by gambiegambo** [winstonjs/winston-daily-rotate-file#110]
I have used winston and winston dairy rotate file version as follow

"winston": "^3.0.0-rc1",
 "winston-daily-rotate-file": "^1.7.2",

and create new logger with

'use-strict'

import winston from 'winston';
import DailyRotateFile from 'winston-daily-rotate-file';
import fs from 'fs';
import shell from 'shelljs';
import os from 'os';

const {
    combine,
    timestamp,
    label,
    printf
} = winston.format;

const myFormat = printf(error => {
    return `${error.timestamp}|[${error.label}]|${error.level}: ${error.message}`;
});

const logDir = '../../app/log';
const tsFormat = () => (new Date()).toLocaleTimeString();
const hostname = os.hostname();

if (!fs.existsSync(logDir)) {
    shell.mkdir('-p', logDir);
}

const authenLogger = winston.createLogger({
    level: 'error',
    format: combine(
        label({
            label: 'right meow!'
        }),
        timestamp(),
        myFormat
    )
});

//`${logDir}/${hostname}_log_authen_fail.log`
authenLogger.configure({
    transports: [
        new DailyRotateFile({
            filename: './log',
            datePattern: 'yyyy-MM-dd.',
            level: 'error'
        })
    ]
});

if (process.env.NODE_ENV !== 'production') {
    authenLogger.add(new winston.transports.Console({
        format: combine(
            label({
                label: 'right meow!'
            }),
            timestamp(),
            myFormat
        ),
        timestamp: tsFormat,
        colorize: true
    }));
}

authenLogger.on('error', function (err) { console.log(err.message) });

authenLogger.error('Test')
module.exports = authenLogger;

and found this error:

E:sourcecode\app\root\node_modules\winston-daily-rotate-file\index.js:282
  var ret = this._stream.write(data);
                        ^

TypeError: Cannot read property 'write' of undefined
    at DailyRotateFile._write (E:\Gam\MynetworkProject\sourcecode\app\root\node_modules\winston-daily-rotate-file\index.js:282:25)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at Writable.write (_stream_writable.js:246:11)
    at DerivedLogger.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:101:20)
    at DerivedLogger.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at DerivedLogger.Readable.push (_stream_readable.js:134:10)
    at DerivedLogger.Transform.push (_stream_transform.js:128:32)
    at DerivedLogger._transform (E:\Gam\MynetworkProject\sourcecode\app\root\node_modules\winston\lib\winston\logger.js:218:8)
    at DerivedLogger.Transform._read (_stream_transform.js:167:10)
    at DerivedLogger.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at DerivedLogger.Writable.write (_stream_writable.js:246:11)
    at DerivedLogger.(anonymous function) [as error] (E:\Gam\MynetworkProject\sourcecode\app\root\node_modules\winston\lib\winston\create-lo
gger.js:45:14)
    at Object.<anonymous> (E:/Gam/MynetworkProject/sourcecode/app/root/logger/authen-logger.js:66:14)
    at Module._compile (module.js:570:32)
    at loader (E:\Gam\MynetworkProject\sourcecode\app\root\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Gam\MynetworkProject\sourcecode\app\root\node_modules\babel-register\lib\
node.js:154:7)
    at Module.load (module.js:487:32)

Please help!!

**Comment by mattberther** [comment]
This transport does not currently work with winston 3.0.0. You can track progress of this at #106.
