### ISSUE TITLE
Typeerrors are not logged in winston configured for DailyRotateFile

### ISSUE THREAD

**Issue by rpusarla** [winstonjs/winston-daily-rotate-file#116]
Hi, 
I have put the below configuration for my logging setup. I have purposefully made changes to a function to throw a typeerror exception which has been unhandled in my code.  But, somehow it's not logging in error.log file. 

```
var logger = require('winston');
require('winston-daily-rotate-file');

logger.emitErrs = true;
logger.configure({    
    level: 'info',    
    transports: [
        new (logger.transports.DailyRotateFile)({
            name: 'errors', filename: 'error.log', datePattern: 'yyyy-MM-dd.', prepend: true, level: 'error', handleExceptions: true, humanReadableUnhandledException: true,
            json: false}),
        new (logger.transports.DailyRotateFile)({ name: 'combined', filename: 'combined.log', datePattern: 'yyyy-MM-dd.', prepend: true})
    ]    
});
```

Below is the error message that's displaying in the console but not in the error.log file.

```
TypeError: Cannot read property 'addItem' of undefined
    at C:\test\main.js:196:26
    at chain.isDataValid (C:\test\main.js:148:13)
    at chain.insert (C:\test\main.js:163:18)
    at C:\test\app\routes.js:111:24
    at Layer.handle [as handle_request] (C:\test\node_modules\express\li
b\router\layer.js:95:5)
    at next (C:\test\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\test\node_modules\express\lib\router\route.js:
112:3)
    at Layer.handle [as handle_request] (C:\test\node_modules\express\li
b\router\layer.js:95:5)
    at C:\test\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\test\node_modules\express\lib\router\
index.js:335:12)
    at next (C:\test\node_modules\express\lib\router\index.js:275:10)
    at urlencodedParser (C:\test\node_modules\body-parser\lib\types\urle
ncoded.js:82:7)
    at Layer.handle [as handle_request] (C:\test\node_modules\express\li
b\router\layer.js:95:5)
    at trim_prefix (C:\test\node_modules\express\lib\router\index.js:317
:13)
    at C:\test\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\test\node_modules\express\lib\router\
index.js:335:12)
```

Can someone please advise me the solution ? FYI, I am using winston@2.4.0.

**Comment by mattberther** [comment]
Neither this component nor winstojs automatically log exceptions. Is your exception handler calling the logger?

``` javascript
try {
  // some code that throws an exception
} catch (e) {
  logger.error(e);
}
```

Please re-open this issue if this is still a problem.

**Comment by rpusarla** [comment]
Thanks Matt for quick response. It worked.
