### ISSUE TITLE
Is this not updated with recent Winston yet (3.x)? I got `this._stream.write(data)` error.

### ISSUE THREAD

**Issue by notalentgeek** [winstonjs/winston-daily-rotate-file#122]
From:

```javascript
  var winston = require('winston');
  require('winston-daily-rotate-file');

  var transport = new (winston.transports.DailyRotateFile)({
    filename: './log',
    datePattern: 'yyyy-MM-dd.',
    prepend: true,
    level: process.env.ENV === 'development' ? 'debug' : 'info'
  });

  var logger = winston.createLogger({ // <-- I only changed this line
    transports: [
      transport
    ]
  });

  logger.info('Hello World!');
```

I got this error:

```
/home/notalentgeek/Desktop/w-1/node_modules/winston-daily-rotate-file/index.js:267
  var ret = this._stream.write(data);
                         ^

TypeError: Cannot read property 'write' of undefined
    at module.exports.DailyRotateFile._write (/home/notalentgeek/Desktop/w-1/node_modules/winston-daily-rotate-file/index.js:267:26)
    at doWrite (_stream_writable.js:407:12)
    at writeOrBuffer (_stream_writable.js:393:5)
    at module.exports.Writable.write (_stream_writable.js:290:11)
    at DerivedLogger.ondata (_stream_readable.js:646:20)
    at DerivedLogger.emit (events.js:165:20)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at DerivedLogger.Readable.push (_stream_readable.js:213:10)
    at DerivedLogger.Transform.push (_stream_transform.js:146:32)
```

**Comment by mattberther** [comment]
Winston 3.0 compatibility is being discussed at #106 and a RC is available at #107.
