### ISSUE TITLE
 options `colorize` and `prettyPrint` fail

### ISSUE THREAD

**Issue by jeantanzj** [winstonjs/winston-daily-rotate-file#131]
node version: 9.10.0
winston-daily-rotate-file version: 3.0.1
```
logger.add(logger.transports.DailyRotateFile, {
                  level: 'error', 
                  filename: 'my.log',
                  timestamp: true,
                  maxFiles: 5,
                  maxsize: 100000000,
                  datePattern: '.yyyy-MM-dd',
                  colorize: true,
                  prettyPrint: true
           })
```

The options `colorize` and `prettyPrint` fail.

For `prettyPrint: true`

```
ReferenceError: util is not defined
at Object.exports.log (/container/node_modules/winston-compat/index.js:183:32)
at DailyRotateFile.log (/container/node_modules/winston-daily-rotate-file/daily-rotate-file.js:109:29)
```

For `colorize: true`

```
/container/node_modules/winston-compat/index.js:160
 ? config.colorize(options.level)
ReferenceError: config is not defined
 at Object.exports.log (/container/node_modules/winston-compat/index.js:160:9)
at DailyRotateFile.log (/container/node_modules/winston-daily-rotate-file/daily-rotate-file.js:109:29)
```

**Comment by mariecl** [comment]
I am seeing the same error.

**Comment by mattberther** [comment]
This is an open issue at https://github.com/winstonjs/winston-compat/issues/3. We can keep track of progress there. I'll close this issue out once that issue is resolved.

/cc @indexzero

**Comment by mattberther** [comment]
Resolved with `winston-daily-rotate-file@3.1.4`.
