### ISSUE TITLE
Query: dailyRotateFile:        SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by thesayyn** [winstonjs/winston-daily-rotate-file#211]
I'm getting this error when querying the logs

```
Exception
 { dailyRotateFile:
       SyntaxError: Unexpected end of JSON input
           at JSON.parse (<anonymous>)
           at add (/Users/thesayyn/Documents/angular projects/tdadmin-server/node_modules/winston-daily-rotate-file/daily-rotate-file.js:256:32)
           at ReadStream.<anonymous> (/Users/thesayyn/Documents/angular projects/tdadmin-server/node_modules/winston-daily-rotate-file/daily-rotate-file.js:211:17)
           at ZoneDelegate.invokeTask (/Users/thesayyn/Documents/angular projects/tdadmin-server/node_modules/zone.js/dist/zone-node.js:421:31)
           at Object.onInvokeTask (Users/thesayyn/Documents/angular_projects/tdadmin-server/node_modules/@angular/core/fesm5/core.js:14088:33)
           at ZoneDelegate.invokeTask (/Users/thesayyn/Documents/angular projects/tdadmin-server/node_modules/zone.js/dist/zone-node.js:420:36)
           at Zone.runTask (/Users/thesayyn/Documents/angular projects/tdadmin-server/node_modules/zone.js/dist/zone-node.js:188:47)
           at ZoneTask.invokeTask (/Users/thesayyn/Documents/angular projects/tdadmin-server/node_modules/zone.js/dist/zone-node.js:496:34)
           at ReadStream.ZoneTask.invoke (/Users/thesayyn/Documents/angular projects/tdadmin-server/node_modules/zone.js/dist/zone-node.js:485:48)
           at ReadStream.emit (events.js:188:13) }


// Creation 
winston.createLogger({
	format: winston.format.combine(
		winston.format.timestamp(),
		winston.format.errors(),
		winston.format.json({ space: 2 })
	),
	transports: [
		new DailyRotateFile({
			dirname: path.join(this.root, 'logs'),
			filename: `${targetId}-%DATE%.log`,
			datePattern: 'YYYY-MM-DD',
			zippedArchive: true,
			maxSize: '20m',
			maxFiles: '10d',
			json: true
		})
	]
});


// Query
logger.query(
	{
		from: new Date(Date.now() - 24 * 60 * 60 * 1000),
		until: new Date(),
		limit: 10,
		start: 0,
		order: 'desc',
		fields: [ 'message' ]
	},
	console.log
);
```

Log file that winston created.
```
{
  "message": "test",
  "level": "info",
  "label": "7d4933",
  "timestamp": "2019-02-07T09:36:49.265Z"
}
{
  "message": "test",
  "level": "info",
  "label": "35a69d",
  "timestamp": "2019-02-07T09:37:47.772Z"
}

```

Versions
"winston": "^3.2.1",
"winston-daily-rotate-file": "^3.6.0",

**Comment by thesayyn** [comment]
The problem caused by winston.format.json({ space: 2 }).

If I remove indentation query just works fine. 

The relevant line is 207 which splits the file by line.

**Comment by mattberther** [comment]
Yes. Indentation causes issues with this functionality. The winston json formatter does not generate a valid json structure when custom custom formatting. Therefore, query relies on each message to be on a single line.
