### ISSUE TITLE
EMFILE error after running NodeJs service after some time

### ISSUE THREAD

**Issue by xbblvsy** [winstonjs/winston-daily-rotate-file#252]
Using winston 3.1.0 and winston winston-daily-rottae-file @3.5.1 and getting EMFILE error after running service for some time:
2019-11-03T11:40:30.268Z '[FileStreamRotator] Failed to store log audit at:' '/apps/AppName/server/logs/.f13e7020269df01c8ab58cab3cd20e9d8c15021b-audit.json' 'Error:' { Error: EMFILE: too many open files, open '/apps/AppName/server/logs/.f13e7020269df01c8ab58cab3cd20e9d8c15021b-audit.json'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at Object.FileStreamRotator.writeAuditLog (/apps/AppName/server/node_modules/file-stream-rotator/FileStreamRotator.js:246:12)
    at Object.FileStreamRotator.addLogToAudit (/apps/AppName/server/node_modules/file-stream-rotator/FileStreamRotator.js:320:27)
    at EventEmitter.<anonymous> (/apps/AppName/server/node_modules/file-stream-rotator/FileStreamRotator.js:437:36)
    at EventEmitter.emit (events.js:182:13)
    at Object.<anonymous> (/apps/AppName/server/node_modules/file-stream-rotator/FileStreamRotator.js:474:24)
    at DailyRotateFile.log (/apps/AppName/server/node_modules/winston-daily-rotate-file/daily-rotate-file.js:141:24)
    at DailyRotateFile._write (/apps/AppName/server/node_modules/winston-transport/index.js:102:17)
    at doWrite (/apps/AppName/server/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/apps/AppName/server/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DailyRotateFile.Writable.write (/apps/AppName/server/node_modules/winston-transport/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.ondata (/apps/AppName/server/node_modules/readable-stream/lib/_stream_readable.js:639:20)
    at DerivedLogger.emit (events.js:182:13)
    at addChunk (/apps/AppName/server/node_modules/readable-stream/lib/_stream_readable.js:296:12)
    at readableAddChunk (/apps/AppName/server/node_modules/readable-stream/lib/_stream_readable.js:278:11)
  errno: -24,
  syscall: 'open',
  code: 'EMFILE',
  path:
   '/apps/AppName/server/logs/.f13e7020269df01c8ab58cab3cd20e9d8c15021b-audit.json' }
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open '/apps/AppName/server/logs/AppName-2019-11-03.log'
Emitted 'error' event at:
    at WriteStream.<anonymous> (/apps/eagleSRE-QueryAPI/server/node_modules/file-stream-rotator/FileStreamRotator.js:538:15)
    at WriteStream.emit (events.js:182:13)
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:141:20)

**Comment by mattberther** [comment]
Could you please provide some additional details, including node version and logger configuration?

**Comment by mattberther** [comment]
Closing due to non-response. If the issue persists, please re-open and provide the requested information.
