### ISSUE TITLE
Feature request: New level option

### ISSUE THREAD

**Issue by leggiero** [winstonjs/winston-daily-rotate-file#262]
Thanks for providing this fantastic module.

Would be great to know if is possible to consider a new `level` option in order to segregate logs per level. Like in the standard [Winston File transport](https://github.com/winstonjs/winston#usage):

`new transports.File({ filename: 'error.log', level: 'error' })`

Thank you!

**Comment by mattberther** [comment]
This should already work - please re-open if you find it does not.

``` javascript
var winston = require('winston');
require('winston-daily-rotate-file');

var transport = new winston.transports.DailyRotateFile({
    filename: './logs/application-%DATE%',
    level: 'error'
});

var logger = winston.createLogger({
    transports: [
        transport
    ]
});

logger.error("This will log to the winston-daily-rotate-file transport.");
logger.info("This will not log to the winston-daily-rotate-file transport.");
```

**Comment by weotch** [comment]
I'm finding that it's not working for me.  Using winston@3.2.1` and winston-daily-rotate-file@4.4.2.  

```js
const dailyErrors = new winston.transports.DailyRotateFile({
  level: 'error',
  filename: 'errors-%DATE%.log',
  format: winston.format.combine(winston.format.timestamp({
    format: 'MM/DD/YYYY HH:mm:ss'
  }), winston.format.errors({
    stack: true
  }), winston.format.printf(function(info) {
    return `${info.timestamp} ${info.level}: ${info.message}\n${info.stack}`;
  }))
});

const winston = winston.createLogger({
  transports: [dailyErrors]
});

```

I'm seeing `info` level messages in my daily log.

**Comment by mattberther** [comment]
@weotch I have an idea of what might be happening here, but before I go too far down that path,cCan you provide an example of how the log messages are being generated, along with an example of the log file?

**Comment by weotch** [comment]
On my winston instance, I'm calling

```js
logger.info("Started")
logger.error("Uncaught exception: ", error) //  A thrown error
```

And the errors log would contain, for example:

```
05/12/2020 09:10:30 info: Starting
05/12/2020 09:10:45 error: Uncaught exception: testing logging
Error: testing logging
    at Orchestrator.isProcessable (/Users/reinhard/Work/xxxxx/order-processor/src/orchestration/Orchestrator.coffee:95:9)
    at Orchestrator.onCreditOrder (/Users/reinhard/Work/xxxxx/order-processor/src/orchestration/Orchestrator.coffee:90:18)
    at Orchestrator.onOrder (/Users/reinhard/Work/xxxxx/order-processor/src/orchestration/Orchestrator.coffee:81:11)
    at /Users/reinhard/Work/xxxxx/order-processor/src/orchestration/Orchestrator.coffee:53:47
    at Orchestrator.captureProcessingErrors (/Users/xxxxx/Work/xxxxx/order-processor/src/orchestration/
```

---

FWIW, I've made a custom formatter to work around for now, that returns `false` if the level isn't `error`

**Comment by mattberther** [comment]
I must be missing something here - the following code works as expected here. Can you please try this and let me know if you see similar results?

```
~/projects/winstonjs/winston-daily-rotate-file master*
❯ cat level-test.js
var winston = require('winston');
require('winston-daily-rotate-file');

const dailyErrors = new winston.transports.DailyRotateFile({
    level: 'error',
    filename: 'errors-%DATE%.log',
    format: winston.format.combine(winston.format.timestamp({
        format: 'MM/DD/YYYY HH:mm:ss'
    }), winston.format.errors({
        stack: true
    }), winston.format.printf(function(info) {
        return `${info.timestamp} ${info.level}: ${info.message}\n${info.stack}`;
    }))
});

const logger = winston.createLogger({
    transports: [dailyErrors]
});

logger.error("This will log to the winston-daily-rotate-file transport.", new Error('testing'));
logger.info("This will not log to the winston-daily-rotate-file transport.");

~/projects/winstonjs/winston-daily-rotate-file master*
❯ rm errors-2020-05-12.log&& node level-test.js

~/projects/winstonjs/winston-daily-rotate-file master*
❯ cat errors-2020-05-12.log
05/12/2020 17:26:31 error: This will log to the winston-daily-rotate-file transport.testing
Error: testing
    at Object.<anonymous> (/Users/matt/projects/winstonjs/winston-daily-rotate-file/test.js:22:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

~/projects/winstonjs/winston-daily-rotate-file master*
❯
```

**Comment by terrisgit** [comment]
Only level of error appears to work. If set level to debug, debug messages don't get there and neither do info. Very strange.
