### ISSUE TITLE
Random fail during unit-tests

### ISSUE THREAD

**Issue by mlarcher** [winstonjs/winston-daily-rotate-file#270]
I am using winston-daily-rotate-file@4.4.2 to test the Winston logger file transport. The test suite is running in a docker container on a Gitlab runner. The problem is that it randomly fails quite often.

Here's how the Winston transport is set up:
```js
  // Create the log directory if it does not exist
  if (!fs.existsSync(logDir)) {
    fs.mkdirSync(logDir);
  }

  transportsList.push(
    new transports.DailyRotateFile({
      filename: `${logDir}/%DATE%_.log`,
      datePattern: 'YYYY-MM-DD',
      level: 'silly',
      format: format.json(),
      maxSize: '20m',
      maxFiles: 2,
    }),
  );
```
and here is the gitlab failed job output:
```
events.js:187
       throw er; // Unhandled 'error' event
       ^
 Error: ENOENT: no such file or directory, open 'targetDir/2020-02-18_.log'
 Emitted 'error' event at:
     at WriteStream.<anonymous> (/data/node_modules/file-stream-rotator/FileStreamRotator.js:677:15)
     at WriteStream.emit (events.js:210:5)
     at WriteStream.EventEmitter.emit (domain.js:476:20)
     at /data/node_modules/graceful-fs/graceful-fs.js:293:14
     at /data/node_modules/graceful-fs/graceful-fs.js:323:16
     at FSReqCallback.oncomplete (fs.js:146:23) {
   errno: -2,
   code: 'ENOENT',
   syscall: 'open',
   path: 'targetDir/2020-02-18_.log'
 }
 Makefile:188: recipe for target '_test-unit-cover' failed
 make: *** [_test-unit-cover] Error 1
 make[3]: *** [Makefile:220: run-in-server_node] Error 2
 make[2]: *** [Makefile:224: make-in-server_node] Error 2
 make[1]: *** [Makefile:76: make-in-server_node] Error 2
 make: *** [Makefile:185: test-unit-cover] Error 2
 make: Leaving directory '/builds/projectname/app/server'
 ERROR: Job failed: command terminated with exit code 1
```
I thought this commit https://github.com/winstonjs/winston-daily-rotate-file/commit/e24407fc4a932e17ff5328db8c95e3b5e33034a2 was intended at fixing this issue, but after upgrading the random test keep on happening.

Please let me know if there is any additional info I can provide.

**Comment by mattberther** [comment]
Thanks for the report. Do you have a Dockerfile and the minimal necessary code to fully reproduce this?

**Comment by mlarcher** [comment]
I don't unfortunately, and as it is happening randomly, it is hard to strip down my application to a minimal test case that still has the bug :/

**Comment by mattberther** [comment]
Do you have the code that generates the error isolated enough that you could share (more than just the transport definition)?

**Comment by mlarcher** [comment]
Sorry for the late reply !

Here is the full test file that triggers the issue:
```js
/* eslint global-require: 0 */
const fs = require('fs');

const { transports } = require('winston');

const mockLogginWinston = jest.fn().mockImplementation(() => new transports.Console());
jest.mock('@google-cloud/logging-winston', () => ({
  LoggingWinston: mockLogginWinston,
}));

const mockSentry = jest.fn().mockImplementation(() => new transports.Console());
jest.mock('winston-transport-sentry-node', () => ({
  default: mockSentry,
}));

describe('logger', () => {
  beforeEach(() => {
    jest.resetModules();
  });

  it('should use the log level from the config', async () => {
    // arrange
    const config = require('../config');
    config.set('logger:transports:logFile:isActive', false);
    config.set('logger:level', 'emerg');

    // act
    const logger = require('../logger');

    // assert
    expect(logger.level).toBe('emerg');
  });

  describe('logFile', () => {
    it('should create the target log directory if `logger:transports:logFile:isActive` is set', async () => {
      // arrange
      const config = require('../config');
      config.set('logger:transports:logFile:isActive', true);
      const targetDir = 'targetDir';
      config.set('logger:transports:logFile:targetDir', targetDir);

      // act
      require('../logger');

      // assert
      expect(fs.existsSync(targetDir)).toBe(true);

      // cleanup
      fs.rmdirSync(targetDir, { recursive: true });
    });

    it('should use a default target directory if none is provided', async () => {
      // arrange
      const defaultDir = 'logs';

      // act
      require('../logger');

      // assert
      expect(fs.existsSync(defaultDir)).toBe(true);

      // cleanup
      fs.rmdirSync(defaultDir, { recursive: true });
    });
  });

  describe('stackdriver', () => {
    it('should use GCP Winston transport if `logger:transports:stackdriver:isActive` is set', async () => {
      // arrange
      const config = require('../config');
      config.set('logger:transports:stackdriver:isActive', true);

      // act
      require('../logger');

      // assert
      expect(mockLogginWinston).toHaveBeenCalled();
    });
  });

  describe('sentry', () => {
    it('should use Sentry transport if `logger:transports:sentry:isActive` is set', async () => {
      // arrange
      const config = require('../config');
      config.set('logger:transports:sentry:isActive', true);

      // act
      require('../logger');

      // assert
      expect(mockSentry).toHaveBeenCalled();
    });
  });
});
```

and the tested logger file:
```js
const { createLogger, format, transports } = require('winston');
require('winston-daily-rotate-file');
const fs = require('fs');
const { LoggingWinston } = require('@google-cloud/logging-winston');
const { default: Sentry } = require('winston-transport-sentry-node');

const config = require('./config');

const transportsList = [];

let silent = false;
if (process.env.TEST_MODE === 'unitTest' && !config.get('logger:testing:preventSilentMode')) {
  silent = true;
}

if (config.get('logger:transports:logFile:isActive')) {
  const logDir = config.get('logger:transports:logFile:targetDir') || 'logs';

  // Create the log directory if it does not exist
  if (!fs.existsSync(logDir)) {
    fs.mkdirSync(logDir);
  }

  transportsList.push(
    new transports.DailyRotateFile({
      filename: `${logDir}/%DATE%_.log`,
      datePattern: 'YYYY-MM-DD',
      level: 'silly',
      format: format.json(),
      maxSize: '20m',
      maxFiles: 2,
    }),
  );
}

if (config.get('logger:transports:stackdriver:isActive')) {
  const loggingWinston = new LoggingWinston({
    // required to report logged errors to the Google Cloud Error Reporting console
    serviceContext: {
      service: 'hm-app',
      version: '0.1',
    },
  });
  transportsList.push(loggingWinston);
} else {
  // make it so JSON.stringify doesn't silently swallow errors
  if (!('toJSON' in Error.prototype)) {
    // eslint-disable-next-line no-extend-native
    Object.defineProperty(Error.prototype, 'toJSON', {
      value() {
        const alt = {};

        Object.getOwnPropertyNames(this).forEach((key) => {
          alt[key] = this[key];
        }, this);

        return alt;
      },
      configurable: true,
      writable: true,
    });
  }

  transportsList.push(
    new transports.Console({
      silent,
      format: format.combine(
        format.colorize(),
        format.printf((info) => {
          const { timestamp, level, message, [Symbol.for('splat')]: splat } = info;
          const metadata = splat ? ` ${JSON.stringify(splat)}` : '';
          return `${timestamp} ${level}: ${message}${metadata}`;
        }),
      ),
    }),
  );
}

if (config.get('logger:transports:sentry:isActive')) {
  const sentryOptions = {
    sentry: {
      dsn: config.get('logger:transports:sentry:dsn'),
    },
    level: 'error',
  };

  transportsList.push(new Sentry(sentryOptions));
}

const logger = createLogger({
  level: config.get('logger:level'),
  format: format.combine(format.timestamp()),
  transports: transportsList,
});

module.exports = logger;
```

Hope this can help

**Comment by mlarcher** [comment]
also, here is another error output, triggered by a different test:
```sh
events.js:187
       throw er; // Unhandled 'error' event
       ^
 Error: ENOENT: no such file or directory, open 'logs/2020-03-18_.log'
 Emitted 'error' event at:
     at WriteStream.<anonymous> (/data/node_modules/file-stream-rotator/FileStreamRotator.js:677:15)
     at WriteStream.emit (events.js:210:5)
     at WriteStream.EventEmitter.emit (domain.js:476:20)
     at /data/node_modules/@jest/core/node_modules/graceful-fs/graceful-fs.js:295:14
     at /data/node_modules/@jest/core/node_modules/graceful-fs/graceful-fs.js:325:16
     at FSReqCallback.oncomplete (fs.js:146:23) {
   errno: -2,
   code: 'ENOENT',
   syscall: 'open',
   path: 'logs/2020-03-18_.log'
 }
 Makefile:200: recipe for target '_test-unit-cover' failed
 make: *** [_test-unit-cover] Error 1
 make[3]: *** [Makefile:223: run-in-server_node] Error 2
 make[2]: *** [Makefile:227: make-in-server_node] Error 2
 make[1]: *** [Makefile:79: make-in-server_node] Error 2
 make: *** [Makefile:197: test-unit-cover] Error 2
 make: Leaving directory '/builds/projectname/app/server'
 ERROR: Job failed: command terminated with exit code 1
```

**Comment by mlarcher** [comment]
any news on this issue ?
