### ISSUE TITLE
Throwing error No such file or directory after running it for sometime

### ISSUE THREAD

**Issue by razat** [winstonjs/winston-daily-rotate-file#276]
I am getting following error after running the code for sometime

const transport = new(winston.transports.DailyRotateFile)({
	filename: 'application-%DATE%.log',
	zippedArchive: true,
	maxSize: '10m',
	maxFiles: 3,
	frequency: '1m'
});

 Am i doing something wrong?

Error: ENOENT: no such file or directory, open 'application-2020-05-29.log.2261'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:132:12
    at FSReqCallback.oncomplete (fs.js:155:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'application-2020-05-29.log.2261'
}

**Comment by mattberther** [comment]
Please describe your configuration in a bit more detail. 

* Which winston version are you using? 
* Which transport version are you using? 
* What OS?
* Are you running this in a clustered environment, using PM2 or some other node process manager?

**Comment by razat** [comment]
Hi Mattberther,

Following configuration i am using
- I am using v4.4.2
- V3.2.1
-  Mac os
-  No i am not running in clustered environment right now

**Comment by mattberther** [comment]
Can you please provide the smallest piece of code that consistently reproduces this problem? Thank you.

**Comment by mattberther** [comment]
Closing due to inactivity. Please reopen if this continues to be a problem.
