### ISSUE TITLE
Why the stacktrace contains winston files ?

### ISSUE THREAD

**Issue by sujithkris** [winstonjs/winston-daily-rotate-file#282]
```
ERROR:
STACK TRACE
TimeoutError: Timeout has occurred
    at Object.exports.clone (/root/projects/myproject-1/node_modules/winston-compat/index.js:33:12)
    at Object.exports.clone (/root/projects/myproject-1/node_modules/winston-compat/index.js:56:54)
    at Object.exports.log (/root/projects/myproject-1/node_modules/winston-compat/index.js:164:45)
    at DailyRotateFile.log (/root/projects/myproject-1/node_modules/winston-daily-rotate-file/daily-rotate-file.js:137:29)
    at transportLog (/root/projects/myproject-1/node_modules/winston/lib/winston/logger.js:234:15)
    at /root/projects/myproject-1/node_modules/winston/node_modules/async/lib/async.js:157:13
    at _each (/root/projects/myproject-1/node_modules/winston/node_modules/async/lib/async.js:57:9)
    at Object.async.each (/root/projects/myproject-1/node_modules/winston/node_modules/async/lib/async.js:156:9)
    at exports.Logger.Logger.log (/root/projects/myproject-1/node_modules/winston/lib/winston/logger.js:246:9)
    at exports.Logger.target.(anonymous function) [as error] (/root/projects/myproject-1/node_modules/winston/lib/winston/common.js:54:18)
at AnonymousObserver.client.getUserDetails.subscribe.err [as _onError] (/root/projects/myproject-1/app/user.js:128:12)
......................
......................
......................

```

Above is the stack trace I am getting when I do `logger.error(err)`

**Implementation**

```
var _transports = [];
_transports.push(new (winston.transports.DailyRotateFile)({
		level: "debug",
		filename: './logs/all.log',
		maxSize: maxLogFileSize,
		datePattern: 'YYYY-MM-DD',
		formatter: formatter,
		timestamp: formattedDate,
		handleExceptions: true,
		humanReadableUnhandledException: true,
		json: false,
		colorize: false,
		zippedArchive: false
	}));

logger = new winston.Logger({
	transports: _transports,
	exitOnError: false
});
```

**Versions**
`winston : 2.4.2`
`winston-daily-rotate-file : 3.9.0`

This looks random and most of the times I am seeing proper stack trace where the topmost line points to the exact line causing error.

**Comment by sujithkris** [comment]
@mattberther Can you help here?

**Comment by mattberther** [comment]
Reviewing your stacktrace, the transport calls the `winston-compat` library which seems to be causing the error. 

https://github.com/winstonjs/winston-daily-rotate-file/blob/4cf25b5bebbb476aedcadc7fec007e6c08128efa/daily-rotate-file.js#L137

Reviewing the `winston-compat` code that is causing the error (https://github.com/winstonjs/winston-compat/blob/bc75d4983570c3ba1d3e1b4d77577adcc45aacc9/index.js#L31-L33), it seems as though your problem might be caused by a custom error object. 

I do not believe this to be an issue with `winston-daily-rotate-file`, and would encourage you to open an issue on the `winston-compat` project if you are unable to resolve this.
