### ISSUE TITLE
Asynchronous function without callback

### ISSUE THREAD

**Issue by davericher** [winstonjs/winston-daily-rotate-file#75]
(node:16486) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
    at makeCallback (fs.js:106:12)
    at Object.fs.unlink (fs.js:1068:14)
    at compressFile (/mnt/nas/code/projects/fsociety/MrNodeBot/node_modules/winston-daily-rotate-file/index.js:588:12)
    at createAndFlush (/mnt/nas/code/projects/fsociety/MrNodeBot/node_modules/winston-daily-rotate-file/index.js:575:7)
    at /mnt/nas/code/projects/fsociety/MrNodeBot/node_modules/winston-daily-rotate-file/index.js:598:16
    at FSReqWrap.oncomplete (fs.js:114:15)

**Comment by mattberther** [comment]
Thanks for the heads up. Resolved with npm 1.4.6.
