### ISSUE TITLE
Function compressFile exception

### ISSUE THREAD

**Issue by dmitriyGarden** [winstonjs/winston-daily-rotate-file#98]
If option zippedArchive set true, the we have the error:
fs.js:1067
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ETXTBSY: text file is busy, unlink '/var/log/winston/2017-10-13.combine.log'
    at Object.fs.unlinkSync (fs.js:1067:18)
    at compressFile (/var/www/project/node_modules/winston-daily-rotate-file/index.js:617:12)
    at createAndFlush (/var/www/project/node_modules/winston-daily-rotate-file/index.js:604:7)
    at /var/www/project/node_modules/winston-daily-rotate-file/index.js:627:16
    at FSReqWrap.oncomplete (fs.js:152:21)

**Comment by mattberther** [comment]
Some long-overdue refactoring of the transport has occurred. A PR is available at #107. Also, a pre-release version has been published to npm. Please `npm install winston-daily-rotate-file@2.0.0-beta` and reopen this issue if the problem remains.
